### ISSUE TITLE
Fix Readme to include makefile instructions

### ISSUE THREAD

**Issue by chadthecoder** [chadthecoder/graphicsProject#4]
Need to add new lines where needed and add instructions to make for windows

**Comment by stedankyi** [comment]
Hi, I am Stephen and I am Ghanaian. I just got my first professional job as a C++ developer although I am by no means great at it. I found this project on an open source website and I want to contribute to this and improve my C++ skills if you don't mind...

**Comment by chadthecoder** [comment]
No problem. I am mostly trying to make changes to the pong game. Feel free to make a pull request. I am still learning about git so I will try my best to implement your requests. Running the make commands should build the project on Windows or Linux. I have not recently tested it on Windows though. @stedankyi

**Comment by stedankyi** [comment]
Hi, thanks for answering me and giving me the chance to contribute. I believe at the moment, I do not have the permissions to create a branch and create a pull request with my changes. Could you give me permissions to publish a branch and create a pull request for the project?

**Comment by stedankyi** [comment]
Also if you could give me some pointers on how you want the ReadMe for the make file should be, kindly let me know.

**Comment by chadthecoder** [comment]
@stedankyi I will try to figure that out as soon as possible. As far as the readme, I didn't have any particular set up. Just as long as it's readable and it gives instructions on how to make the projects.

**Comment by chadthecoder** [comment]
@stedankyi You should be able to get the permissions now.

**Comment by chadthecoder** [comment]
@stedankyi I found a better way to submit pull requests. You can fork the repo and create your own branch. Here is a YouTube video explaining in 100 seconds. It is too late to get the sticker, but very helpful. https://www.youtube.com/watch?v=8lGpZkjnkt4&t=12s

**Comment by stedankyi** [comment]
Hi @chadthecoder 
Sorry I've been MIA for a while, I kinda got sick and I was off work for a week. I am just coming back.
Thanks for the resources you pointed me to. I have learned a lot from them. I am going to look at he other issues and see how I could contribute to them. Thanks
